name: Build and Publish NPM Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true

      # Build and publish packages
      - name: Install dependencies and publish packages
        run: |          
          echo "Building and publishing packages"
          
          # Install yarn
          npm install -g yarn

          # Compile & test
          yarn install 
          yarn tsc 
          yarn build
          yarn test

          # Publish
          npm publish ./plugins/emma-common/ --dry-run
          npm publish ./plugins/emma-backend/ --dry-run
          npm publish ./plugins/emma/ --dry-run

          # Create Git tag for packages
          # PACKAGE_VERSION=$(node -p "require('./package.json').version")
          # git tag "v$PACKAGE_VERSION"
          # git push origin "v$PACKAGE_VERSION"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
