name: Build and Publish NPM Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true

      # Build and publish common package
      - name: Install dependencies and publish common package
        run: |
          cd ./plugins/emma-common
          
          echo "Building and publishing common package"
          
          # Install yarn
          npm install -g yarn

          # Install dependencies
          yarn install 

          # Build the package
          yarn build

          # Publish to NPM
          npm publish

          # Create Git tag for common package
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git tag "common-v$PACKAGE_VERSION"
          git push origin "common-v$PACKAGE_VERSION"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build and publish backend package
      - name: Install dependencies and publish backend package
        run: |
          cd ./plugins/emma-backend
          
          echo "Building and publishing backend package"
          
          # Install yarn
          npm install -g yarn

          # Install dependencies
          yarn install 

          # Build the package
          yarn build

          # Publish to NPM
          npm publish

          # Create Git tag for backend package
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git tag "backend-v$PACKAGE_VERSION"
          git push origin "backend-v$PACKAGE_VERSION"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build and publish frontend package
      - name: Install dependencies and publish frontend package
        run: |
          cd ./plugins/emma
          
          echo "Building and publishing frontend package"
          
          # Install yarn
          npm install -g yarn

          # Install dependencies
          yarn install 

          # Build the package
          yarn build

          # Publish to NPM
          npm publish

          # Create Git tag for frontend package
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git tag "frontend-v$PACKAGE_VERSION"
          git push origin "frontend-v$PACKAGE_VERSION"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
